"""col

Revision ID: 82df129621dc
Revises: 8f203d9ea832
Create Date: 2020-07-17 16:54:35.162229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82df129621dc'
down_revision = '8f203d9ea832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_author_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_author_fkey', 'posts', 'users', ['author'], ['id'])
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
